# -*- coding: utf-8 -*-
for i in range(97, 97 + 26):
    if i == 97:print(str(i)+" e a")
    if i == 98:print(str(i)+" e b")
    if i == 99:print(str(i)+" e c")
    if i == 100:print(str(i)+" e d")
    if i == 101:print(str(i)+" e e")
    if i == 102:print(str(i)+" e f")
    if i == 103:print(str(i)+" e g")
    if i == 104:print(str(i)+" e h")
    if i == 105:print(str(i)+" e i")
    if i == 106:print(str(i)+" e j")
    if i == 107:print(str(i)+" e k")
    if i == 108:print(str(i)+" e l")
    if i == 109:print(str(i)+" e m")
    if i == 110:print(str(i)+" e n")
    if i == 111:print(str(i)+" e o")
    if i == 112:print(str(i)+" e p")
    if i == 113:print(str(i)+" e q")
    if i == 114:print(str(i)+" e r")
    if i == 115:print(str(i)+" e s")
    if i == 116:print(str(i)+" e t")
    if i == 117:print(str(i)+" e u")
    if i == 118:print(str(i)+" e v")
    if i == 119:print(str(i)+" e w")
    if i == 120:print(str(i)+" e x")
    if i == 121:print(str(i)+" e y")
    if i == 122:print(str(i)+" e z")



